### ISSUE TITLE
use RandomizedSearchCV and estmator is RandomForestClassifier  have bug?

### ISSUE THREAD

**Issue by liyingkun1237** [dask/dask-ml#159]
run code is about:
``` python
print(__doc__)

import numpy as np

from time import time
from scipy.stats import randint as sp_randint

# from sklearn.model_selection import GridSearchCV
# from sklearn.model_selection import RandomizedSearchCV
from dask_searchcv import GridSearchCV
from dask_searchcv import RandomizedSearchCV
from sklearn.datasets import load_digits
from sklearn.ensemble import RandomForestClassifier

# get some data
digits = load_digits()
X, y = digits.data, digits.target

# build a classifier
clf = RandomForestClassifier(n_estimators=20)


# Utility function to report best scores
def report(results, n_top=3):
    for i in range(1, n_top + 1):
        candidates = np.flatnonzero(results['rank_test_score'] == i)
        for candidate in candidates:
            print("Model with rank: {0}".format(i))
            print("Mean validation score: {0:.3f} (std: {1:.3f})".format(
                results['mean_test_score'][candidate],
                results['std_test_score'][candidate]))
            print("Parameters: {0}".format(results['params'][candidate]))
            print("")


# specify parameters and distributions to sample from
param_dist = {"max_depth": [3, None],
              "max_features": sp_randint(1, 11),
              "min_samples_split": sp_randint(2, 11),
              "min_samples_leaf": sp_randint(1, 11),
              "bootstrap": [True, False],
              "criterion": ["gini", "entropy"]}

# run randomized search
n_iter_search = 20
random_search = RandomizedSearchCV(clf, param_distributions=param_dist,
                                   n_iter=n_iter_search)

start = time()
random_search.fit(X, y)
print("RandomizedSearchCV took %.2f seconds for %d candidates"
      " parameter settings." % ((time() - start), n_iter_search))
report(random_search.cv_results_)

# use a full grid over all parameters
param_grid = {"max_depth": [3, None],
              "max_features": [1, 3, 10],
              "min_samples_split": [2, 3, 10],
              "min_samples_leaf": [1, 3, 10],
              "bootstrap": [True, False],
              "criterion": ["gini", "entropy"]}

# run grid search
grid_search = GridSearchCV(clf, param_grid=param_grid)
start = time()
grid_search.fit(X, y)

print("GridSearchCV took %.2f seconds for %d candidate parameter settings."
      % (time() - start, len(grid_search.cv_results_['params'])))
report(grid_search.cv_results_)
```

the error is :
```cmd
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-139-ecec65d20380>", line 50, in <module>
    random_search.fit(X, y)
  File "/root/anaconda3/lib/python3.6/site-packages/dask_searchcv/model_selection.py", line 867, in fit
    out = scheduler(dsk, keys, num_workers=n_jobs)
  File "/root/anaconda3/lib/python3.6/site-packages/dask/threaded.py", line 75, in get
    pack_exception=pack_exception, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/dask/local.py", line 521, in get_async
    raise_exception(exc, tb)
  File "/root/anaconda3/lib/python3.6/site-packages/dask/compatibility.py", line 60, in reraise
    raise exc
File "/root/anaconda3/lib/python3.6/site-packages/dask/local.py", line 290, in execute_task
    result = _execute_task(task, data)
  File "/root/anaconda3/lib/python3.6/site-packages/dask/local.py", line 271, in _execute_task
    return func(*args2)
  File "/root/anaconda3/lib/python3.6/site-packages/dask_searchcv/methods.py", line 280, in fit_and_score
    fields, params, fit_params)
  File "/root/anaconda3/lib/python3.6/site-packages/dask_searchcv/methods.py", line 216, in fit
    est.fit(X, y, **fit_params)
  File "/root/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/forest.py", line 316, in fit
    random_state=random_state)
  File "/root/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/base.py", line 125, in _make_estimator
    estimator = clone(self.base_estimator_)
  File "/root/anaconda3/lib/python3.6/site-packages/sklearn/base.py", line 60, in clone
    new_object_params = estimator.get_params(deep=False)
  File "/root/anaconda3/lib/python3.6/site-packages/sklearn/base.py", line 241, in get_params
    warnings.filters.pop(0)
IndexError: pop from empty list

```

**Comment by lesteve** [comment]
It does ring a bell as an old scikit-learn bug. Can you make sure you are using scikit-learn 0.19.1 which is the latest released version?

**Comment by lesteve** [comment]
Yep this should be fixed in 0.19.1. For completeness, the scikit-learn issue is https://github.com/scikit-learn/scikit-learn/issues/7346.

**Comment by TomAugspurger** [comment]
Thanks for the link @lesteve.

Closing this since it's fixed upstream, and working around it would be rather difficult.

**Comment by wtbarnes** [comment]
Using scikit-learn 0.19.1, I'm still encountering this bug using the code provided above (as well as in my own work) so I don't think the upstream fix has actually solved this problem.  `RandomizedSearchCV` seems to not be a problem and it is only in `GridSearchCV` that this error pops up.

Version Info:
* scikit-learn 0.19.1
* dask 0.18.0
* dask-ml 0.6.0
* dask-searchcv 0.2.0
* distributed 1.22.0

**Comment by TomAugspurger** [comment]
I'm not able to reproduce with those versions in a 3.6 environment running the following:

```
import numpy as np

from time import time

# from sklearn.model_selection import GridSearchCV
# from sklearn.model_selection import RandomizedSearchCV
from dask_ml.model_selection import GridSearchCV
from sklearn.datasets import load_digits
from sklearn.ensemble import RandomForestClassifier

# get some data
digits = load_digits()
X, y = digits.data, digits.target

# build a classifier
clf = RandomForestClassifier(n_estimators=20)


# Utility function to report best scores
def report(results, n_top=3):
    for i in range(1, n_top + 1):
        candidates = np.flatnonzero(results['rank_test_score'] == i)
        for candidate in candidates:
            print("Model with rank: {0}".format(i))
            print("Mean validation score: {0:.3f} (std: {1:.3f})".format(
                results['mean_test_score'][candidate],
                results['std_test_score'][candidate]))
            print("Parameters: {0}".format(results['params'][candidate]))
            print("")


# use a full grid over all parameters
param_grid = {"max_depth": [3, None],
              "max_features": [1, 3, 10],
              "min_samples_split": [2, 3, 10],
              "min_samples_leaf": [1, 3, 10],
              "bootstrap": [True, False],
              "criterion": ["gini", "entropy"]}

# run grid search
grid_search = GridSearchCV(clf, param_grid=param_grid)
start = time()
grid_search.fit(X, y)
```

what stacktrace do you get @wtbarnes ?

**Comment by wtbarnes** [comment]
@TomAugspurger  thanks for the quick reply. I just created a clean env with recent versions of all packages (just to be safe) and am still getting this error. The full traceback is:

```python traceback
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-5-ba93e591f43c> in <module>()
      4 grid_search = GridSearchCV(clf, param_grid=param_grid)
      5 start = time()
----> 6 grid_search.fit(X, y)

~/anaconda3/envs/sklearn-dask-ml-test/lib/python3.6/site-packages/dask_searchcv/model_selection.py in fit(self, X, y, groups, **fit_params)
    865         scheduler = _normalize_scheduler(self.scheduler, n_jobs)
    866 
--> 867         out = scheduler(dsk, keys, num_workers=n_jobs)
    868 
    869         results = handle_deprecated_train_score(out[0], self.return_train_score)

~/anaconda3/envs/sklearn-dask-ml-test/lib/python3.6/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, **kwargs)
     73     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
     74                         cache=cache, get_id=_thread_get_id,
---> 75                         pack_exception=pack_exception, **kwargs)
     76 
     77     # Cleanup pools associated to dead threads

~/anaconda3/envs/sklearn-dask-ml-test/lib/python3.6/site-packages/dask/local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    519                         _execute_task(task, data)  # Re-execute locally
    520                     else:
--> 521                         raise_exception(exc, tb)
    522                 res, worker_id = loads(res_info)
    523                 state['cache'][key] = res

~/anaconda3/envs/sklearn-dask-ml-test/lib/python3.6/site-packages/dask/compatibility.py in reraise(exc, tb)
     67         if exc.__traceback__ is not tb:
     68             raise exc.with_traceback(tb)
---> 69         raise exc
     70 
     71 else:

~/anaconda3/envs/sklearn-dask-ml-test/lib/python3.6/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    288     try:
    289         task, data = loads(task_info)
--> 290         result = _execute_task(task, data)
    291         id = get_id()
    292         result = dumps((result, id))

~/anaconda3/envs/sklearn-dask-ml-test/lib/python3.6/site-packages/dask/local.py in _execute_task(arg, cache, dsk)
    269         func, args = arg[0], arg[1:]
    270         args2 = [_execute_task(a, cache) for a in args]
--> 271         return func(*args2)
    272     elif not ishashable(arg):
    273         return arg

~/anaconda3/envs/sklearn-dask-ml-test/lib/python3.6/site-packages/dask_searchcv/methods.py in fit_and_score(est, cv, X, y, n, scorer, error_score, fields, params, fit_params, return_train_score)
    278     y_test = cv.extract(X, y, n, False, False)
    279     est_and_time = fit(est, X_train, y_train, error_score,
--> 280                        fields, params, fit_params)
    281     if not return_train_score:
    282         X_train = y_train = None

~/anaconda3/envs/sklearn-dask-ml-test/lib/python3.6/site-packages/dask_searchcv/methods.py in fit(est, X, y, error_score, fields, params, fit_params)
    214         try:
    215             est = set_params(est, fields, params)
--> 216             est.fit(X, y, **fit_params)
    217         except Exception as e:
    218             if error_score == 'raise':

~/anaconda3/envs/sklearn-dask-ml-test/lib/python3.6/site-packages/sklearn/ensemble/forest.py in fit(self, X, y, sample_weight)
    314             for i in range(n_more_estimators):
    315                 tree = self._make_estimator(append=False,
--> 316                                             random_state=random_state)
    317                 trees.append(tree)
    318 

~/anaconda3/envs/sklearn-dask-ml-test/lib/python3.6/site-packages/sklearn/ensemble/base.py in _make_estimator(self, append, random_state)
    128 
    129         if random_state is not None:
--> 130             _set_random_states(estimator, random_state)
    131 
    132         if append:

~/anaconda3/envs/sklearn-dask-ml-test/lib/python3.6/site-packages/sklearn/ensemble/base.py in _set_random_states(estimator, random_state)
     50     random_state = check_random_state(random_state)
     51     to_set = {}
---> 52     for key in sorted(estimator.get_params(deep=True)):
     53         if key == 'random_state' or key.endswith('__random_state'):
     54             to_set[key] = random_state.randint(MAX_RAND_SEED)

~/anaconda3/envs/sklearn-dask-ml-test/lib/python3.6/site-packages/sklearn/base.py in get_params(self, deep)
    239                     continue
    240             finally:
--> 241                 warnings.filters.pop(0)
    242 
    243             # XXX: should we rather test if instance of estimator?

IndexError: pop from empty list
```

and for completeness here are is the relevant package info,
```
# Name                    Version                   Build  Channel
dask                      0.18.1                   py36_0
dask-core                 0.18.1                   py36_0
dask-glm                  0.1.0            py36h1ff08bd_0
dask-ml                   0.6.0            py36h14c3975_0
dask-searchcv             0.2.0            py36hae2c3c3_0
distributed               1.22.0                   py36_0
mkl                       2018.0.3                      1
mkl_fft                   1.0.1            py36h3010b51_0
mkl_random                1.0.1            py36h629b387_0
msgpack-python            0.5.6            py36h6bb024c_0
numpy                     1.14.5           py36hcd700cb_0
numpy-base                1.14.5           py36hdbf6ddf_0
pandas                    0.23.1           py36h637b7d7_0
python                    3.6.6                hc3d631a_0
scikit-learn              0.19.1           py36h7aa7ec6_0
scipy                     1.1.0            py36hfc37229_0
toolz                     0.9.0                    py36_0
tornado                   5.0.2                    py36_0
```

**Comment by TomAugspurger** [comment]
Ah, looks like this wasn't backported for 0.19.1: https://github.com/scikit-learn/scikit-learn/pull/9569#issuecomment-344081597.

You could try on scikit-learn master, and I think there's a 0.20 release in the works.

**Comment by wtbarnes** [comment]
@TomAugspurger Will try with master. Thanks!

**Comment by TomAugspurger** [comment]
Probably not. I think that 0.20 is reasonably close, and scikit-learn doesn't really have enough development resources to maintain backport branches.
